### **Taller 1: Operaciones básicas de álgebra lineal**

En esta notebook implementaremos las operaciones básicas de álgebra lineal entre vectores y matrices. Antes de observar cómo NumPy realiza estas operaciones de forma eficiente y escalable, pensaremos en cómo implementarlas manualmente (Ej. 1 y 2 de la Guía 1).

#### **Operaciones con vectores**

In [17]:
def suma_vectores(u, v):
    if len(v) != len(v):
        raise ValueError("Los vectores deben tener la misma dimensión")
    else:
        resultado= []
        for i in range(len(u)):
            resultado.append(u[i]+v[i])
        return resultado

In [19]:
def resta_vectores(u, v):
    if len(v) != len(v):
        raise ValueError("Los vectores deben tener la misma dimensión")
    else:
        resultado= []
        for i in range(len(u)):
            resultado.append(u[i]-v[i])
        return resultado

In [20]:
def multiplicacion_escalar_vector(k, v):
    resultado= []
    for i in range(len(u)):
        resultado.append(k*v[i])
    return resultado

In [21]:
def producto_escalar(u, v):
    if len(u) != len(v):
        raise ValueError("Los vectores deben tener la misma dimensión")
    else:
        resultado= []
        for i in range(len(u)):
            resultado.append(u[i]*v[i])
        return resultado

Realicemos los cálculos con un ejemplo particular de vectores.

In [22]:
u = [1, 2, 3, 4]
v = [5, 6, 7, 8]

print(f"u = {u}")
print(f"v = {v}")
print(f"u + v: {suma_vectores(u, v)}")
print(f"u - v: {resta_vectores(u, v)}")
print(f"3u: {multiplicacion_escalar_vector(3, u)}")
print(f"u·v: {producto_escalar(u, v)}")

u = [1, 2, 3, 4]
v = [5, 6, 7, 8]
u + v: [6, 8, 10, 12]
u - v: [-4, -4, -4, -4]
3u: [3, 6, 9, 12]
u·v: [5, 12, 21, 32]


#### **Operaciones con matrices**

In [ ]:
def suma_matrices(A, B):
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Las matrices deben tener las mismas dimensiones")
    else:
        resultado = []
        for i in range(len(A)):
            fila = []
            for j in range(len(B[0])):
                fila.append(A[i][j] + B[i][j])
            resultado.append(fila)
            
        return resultado      

In [ ]:
def resta_matrices(A, B):
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Las matrices deben tener las mismas dimensiones")
    else:
        resultado = []
        for i in range(len(A)):
            fila = []
            for j in range(len(B[0])):
                fila.append(A[i][j] - B[i][j])
            resultado.append(fila)    
        return resultado 

In [46]:
def multiplicacion_escalar_matriz(k, A):
    resultado = []
    for i in range(len(A)):
        fila = []
        for j in range(len(A[0])):
                fila.append(A[i][j]*k)
        resultado.append(fila)
            
    return resultado 

In [52]:
def multiplicacion_matriz_vector(A, v):
    if len(A[0]) != len(v):
        raise ValueError("El número de columnas de la matriz debe coincidir con la longitud del vector")
    else:
        resultado = []
        for i in range(len(A)):
            fila = []
            for j in range(len(A[0])):
                    fila.append(A[i][j] * v[j])
            suma=0
            for k in range(len(fila)): suma=suma+fila[k]
            resultado.append(suma)
                
        return resultado 

In [59]:
def multiplicacion_matrices(A, B):
    if len(A[0]) != len(B):
        raise ValueError("El número de columnas de A debe coincidir con el número de filas de B")
    else:
        resultado = []
        for i in range(len(A)):
            resultado.append([]) # nueva fila
            for j in range(len(B[0])):
                # Calculamos el producto interno entre la fila i de A con la columna j de B
                suma=0
                for k in range(len(B)): # recorro todas las filas de B
                    suma+=A[i][k]*B[k][j]
                resultado[i].append(suma)                        
        return resultado 

Función para imprimir una matriz cualesquiera:

In [60]:
def imprimir_matriz(matrix):
    print("[", end=" ")
    for i, row in enumerate(matrix):
        if i > 0:
            print("  ", end="")
        if i == len(matrix) - 1:
            print(" ".join(map(str, row)), end=" ]\n")
        else:
            print(" ".join(map(str, row)))

Comprobamos los cálculos con un ejemplo particular de matrices.

In [61]:
A = [
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
]

B = [
    [3, 3, 3],
    [2, 2, 2],
    [1, 1, 1]
]

v = [1, 2, 3]

imprimir_matriz(A)
imprimir_matriz(B)
print(f"Vector v = {v}\n")

print("Suma A + B:")
imprimir_matriz(suma_matrices(A, B))

print("Resta A - B:")
imprimir_matriz(resta_matrices(A, B))

print("Producto escalar 2A:")
imprimir_matriz(multiplicacion_escalar_matriz(2, A))

print("Producto matriz vector Av:")
resultado = multiplicacion_matriz_vector(A, v)
print(f"  {resultado}")

print("Producto AB:")
imprimir_matriz(multiplicacion_matrices(A, B))

[ 1 1 1
  2 2 2
  3 3 3 ]
[ 3 3 3
  2 2 2
  1 1 1 ]
Vector v = [1, 2, 3]

Suma A + B:
[ 4 4 4
  4 4 4
  4 4 4 ]
Resta A - B:
[ -2 -2 -2
  0 0 0
  2 2 2 ]
Producto escalar 2A:
[ 2 2 2
  4 4 4
  6 6 6 ]
Producto matriz vector Av:
  [6, 12, 18]
Producto AB:
[ 6 6 6
  12 12 12
  18 18 18 ]


#### **Operaciones de vectores y matrices con NumPy**

Ahora aprenderemos a representar vectores y matrices utilizando NumPy, y veremos cómo implementa esta librería las operaciones básicas de álgebra lineal que realizamos manualmente antes.

¿Qué ventajas trae NumPy frente a las implementaciones manuales?
- Operaciones vectorizadas (sin bucles explícitos en Python).
- Mucho más rápido para grandes volúmenes de datos.
- Sintaxis natural: `u + v`, `3 * u`, `u @ v`

Importamos la librería de NumPy (recuerden configurar adecuadamente el entorno).

In [62]:
import numpy as np

Veamos cómo se representan los vectores y matrices dentro de NumPy.

In [63]:
u = np.array([1, 2, 3])
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Vector:\n", u)
print("\nMatriz:\n", A)

Vector:
 [1 2 3]

Matriz:
 [[1 2 3]
 [4 5 6]]


Una función muy útil de NumPy es `reshape(a, b)`, la cual permite redimensionar los tamaños de vectores y matrices, o incluso convertir una matriz a un vector (aplanar).

In [64]:
# Convertir vector en matriz
B = np.array([1, 2, 3, 4, 5, 6])
B = A.reshape(2, 3)  # Matriz de 2 filas y 3 columnas 

# Convertir matriz en vector
v = np.array([
    [1, 2],
    [3, 4]
])
v = v.reshape(-1)  # Vector columna con todos los valores de la matriz 

print("Vector:\n", v)
print("\nMatriz:\n", B)

Vector:
 [1 2 3 4]

Matriz:
 [[1 2 3]
 [4 5 6]]


Volvamos a realizar las operaciones anteriores ahora con NumPy.

In [65]:
u = np.array([1, 2, 3, 4])
v = np.array([5, 6, 7, 8])

print(f"u =", u)
print(f"v =", v)
print(f"u + v:", u + v)
print(f"u - v:", u - v)
print(f"3u:", 3 * u)
print(f"u · v:", u @ v)  # Otra forma para calcular el producto interno es np.dot(u, v)

u = [1 2 3 4]
v = [5 6 7 8]
u + v: [ 6  8 10 12]
u - v: [-4 -4 -4 -4]
3u: [ 3  6  9 12]
u · v: 70


In [66]:
A = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
])

B = np.array([
    [3, 3, 3],
    [2, 2, 2],
    [1, 1, 1]
])

v = np.array([1, 2, 3])

print("A:\n", A)
print("B:\n", B)
print("v =", v)

print("\nA + B:\n", A + B)
print("A - B:\n", A - B)
print("2A:\n", 2 * A)
print("Av:\n", A @ v)  # np.dot(A, v)
print("AB:\n", A @ B)  # np.dot(A, B)

A:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
B:
 [[3 3 3]
 [2 2 2]
 [1 1 1]]
v = [1 2 3]

A + B:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
A - B:
 [[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]
2A:
 [[2 2 2]
 [4 4 4]
 [6 6 6]]
Av:
 [ 6 12 18]
AB:
 [[ 6  6  6]
 [12 12 12]
 [18 18 18]]
